### ISSUE TITLE
UnsatisfiedLinkError: opencv_java310.dll

### ISSUE THREAD

**Issue by SHS-Programmers** [TheGuyWhoCodes/LiftTracker#7]
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\557547>cd \Users\557547\Desktop\LiftTracker

C:\Users\557547\Desktop\LiftTracker>java -jar LiftTracker.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: no C:/Users/557547/Downloads/opencv/build/java/x86/opencv_java310.dll in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at Processing.<clinit>(Processing.java:43)

C:\Users\557547\Desktop\LiftTracker>
```

So, we have made sure to link the proper files for OpenCV even adding the dll library in eclipse. However, I am continuing to get this error and am unsure as to where to go from here.

**Comment by SHS-Programmers** [comment]
Moved all required libraries into LiftTracker.jar directory and ran from there.
